DROP TABLE IF EXISTS retrieval_chunk CASCADE;
DROP TABLE IF EXISTS job_description CASCADE;
DROP TABLE IF EXISTS email CASCADE;
DROP TABLE IF EXISTS application CASCADE;
DROP TABLE IF EXISTS position_alias CASCADE;
DROP TABLE IF EXISTS company_alias CASCADE;
DROP TABLE IF EXISTS position CASCADE;
DROP TABLE IF EXISTS company CASCADE;
